services:
  otterwiki-init:
    restart: no
    image: alpine:3.20.1
    user: 0:0
    command:
    - sh
    - -c
    - |
      apk add sqlite
      cat << EOF | sqlite3 /app-data/db.sqlite
      PRAGMA foreign_keys=OFF;
      BEGIN TRANSACTION;
      DROP TABLE IF EXISTS user;
      CREATE TABLE user (
              id INTEGER NOT NULL,
              name VARCHAR(128),
              email VARCHAR(128),
              password_hash VARCHAR(512),
              first_seen DATETIME,
              last_seen DATETIME,
              is_approved BOOLEAN,
              is_admin BOOLEAN,
              email_confirmed BOOLEAN,
              allow_read BOOLEAN,
              allow_write BOOLEAN,
              allow_upload BOOLEAN,
              provider VARCHAR(8),
              PRIMARY KEY (id)
      );
      INSERT INTO user VALUES(2,'John Ldap','john@ldap.org',NULL,'2024-12-01 19:28:13.273738','2024-12-01 19:28:13.273750',1,1,1,1,1,1,'ldap');
      INSERT INTO user VALUES(3,'Fulano','fulano@ldap.org',NULL,'2024-12-01 19:28:49.696271','2024-12-01 19:28:49.696281',1,0,0,1,1,0,'ldap');
      INSERT INTO user VALUES(4,'Max','max@ldap.org',NULL,'2024-12-01 19:29:11.958025','2024-12-01 19:29:11.958039',1,0,0,1,1,1,'ldap');
      COMMIT;
      EOF
      chown 33:33 /app-data/db.sqlite
    volumes:
    - app-data:/app-data
  otterwiki:
    depends_on:
    - otterwiki-init
    - ldap
    image: otterwiki-test-ldap
    build:
      context: ../../..
      dockerfile: docker/Dockerfile.slim
    ports:
    - "8080:8080"
    environment:
    - LOG_LEVEL=DEBUG
    - LDAP_URI=ldap://ldap:389
    - LDAP_USERNAME=cn=Manager,dc=ldap,dc=local
    - LDAP_PASSWORD=secret
    - LDAP_BASE=dc=ldap,dc=local
    - LDAP_SCOPE=subtree
    - LDAP_DOMAIN=ldap.org
    volumes:
    - app-data:/app-data
  ldap:
    image: otterwiki-example-ldap
    build: example-ldap
volumes:
  app-data:
